server:
  port: 8769

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: service-ribbon
    api-order:
      path: /api-order/**
      serviceId: service-feign